
sensors = ["copper",
		  "lead",
		  "metaglass",
		  "graphite",
		  "sand",
		  "coal",
		  "titanium",
		  "thorium",
		  "scrap",
		  "silicon",
		  "plastanium",
		  "phase-fabric",
		  "surge-alloy",
		  "spore-pod",
		  "blast-compound",
		  "pyratite",
		  "beryllium",
		  "tungsten",
		  "oxide",
		  "carbide",
		  "water",
		  "slag",
		  "oil",
		  "cryofluid",
		  "neoplasm",
		  "arkycite",
		  "ozone",
		  "hydrogen",
		  "nitrogen",
		  "cyanogen",
		  "totalItems",
		  "firstItem",
		  "totalLiquids",
		  "totalPower",
		  "itemCapacity",
		  "liquidCapacity",
		  "powerCapacity",
		  "powerNetStored",
		  "powerNetCapacity",
		  "powerNetIn",
		  "powerNetOut",
		  "ammo",
		  "ammoCapacity",
		  "health",
		  "maxHealth",
		  "heat",
		  "shield",
		  "efficiency",
		  "progress",
		  "timescale",
		  "rotation",
		  "x",
		  "y",
		  "shootX",
		  "shootY",
		  "size",
		  "dead",
		  "range",
		  "shooting",
		  "boosting",
		  "mineX",
		  "mineY",
		  "mining",
		  "speed",
		  "team",
		  "type",
		  "flag",
		  "controlled",
		  "controller",
		  "name",
		  "payloadCount",
		  "payloadType",
		  "id",
		  "enabled",
		  "config",
		  "color"]


defaultLibs = {
			   "memory":
			   {
				   "write": ["var", "building", "index"],
				   "read": ["var", "building", "index"]
			   },


			   "draw":
			   {
					"flush": ["building"],
			   		"clear": ["r", "g", "b"],
			   		"color": ["r", "g", "b", "a"],
			   		"col": ["color"],
			   		"stroke": ["width"],
			   		"line": ["x1", "y1", "x2", "y2"],
			   		"rect": ["x", "y", "width", "height"],
			   		"lineRect": ["x", "y", "width", "height"],
			   		"poly": ["x", "y", "sides", "radius", "rotation"],
			   		"linePoly": ["x", "y", "sides", "radius", "rotation"],
			   		"triangle": ["x1", "y1", "x2", "y2", "x3", "y3"],
			   		"image": ["x", "y", "image", "size", "rotation"]
			   },

			  "print":
			   {
				   "flush": ["building"],
					"add": ["text"]
			   },

			  "block":
			   {
					"enabled": ["building", "mode"],
					"shoot": ["building", "x", "y", "mode"],
					"shootp": ["building", "unit", "mode"],
					"config": ["building", "config"],
					"color": ["building", "col"],
					"sensor": ["var", "building", "type"],
					"radar": ["filter1", "filter2", "filter3", "sortType", "building", "sortMode", "var"],
					"getlink": ["var", "index"]
			   },

			  "utils":

			   {
					"wait": ["sec"],
					"stop": [],
					"end": []
			   },

			  "unit":
			   {
					"bind": ["unitType"],
					"move": ["x", "y"],
					"idle": [],
					"stop": [],
					"autoPathfind": [],
					"unbind": [],
					"approach": ["x", "y", "radius"],
					"pathfind": ["x", "y"],
					"boost": ["mode"],
					"target": ["x", "y", "mode"],
					"targetp": ["unit", "mode"],
					"itemDrop": ["building", "amount"],
					"itemTake": ["building", "itemType", "amount"],
					"payDrop": [],
					"payTake": ["mode"],
					"payEnter": [],
					"mine": ["x", "y"],
					"flag": ["value"],
					"build": ["x", "y", "block", "rotation", "config"],
					"getBlock": ["x", "y", "varType", "varBuilding", "varFloor"],
					"within": ["x", "y", "radius", "var"],
					"radar": ["filter1", "filter2", "filter3", "sortType", "sortMode", "var"],
					"locateBuilding": ["group", "enemy", "varX", "varY", "varFound", "varBuilding"],
					"locateOre": ["ore", "varX", "varY", "varFound"],
					"locateSpawn": ["varX", "varY", "varFound", "varBuilding"],
					"locateDamaged": ["varX", "varY", "varFound", "varBuilding"]
			   },

			  "math":
			   {

			   }
}

consts = [
	"@this",
	"@thisx",
	"@thisy",
	"@mapw",
	"@maph",
	"@ipt",
	"@tick",
	"@time",
	"@links",
	"@counter",
	"@unit",
	"@flare",
	"@dagger",
	"@mace",
	"@fortress",
	"@scepter",
	"@reign",
	"@nova",
	"@pulsar",
	"@quasar",
	"@vela",
	"@corvus",
	"@crawler",
	"@atrax",
	"@spiroct",
	"@arkyd",
	"@toxopid",
	"@horizon",
	"@zenith",
	"@antumbra",
	"@eclipse",
	"@mono",
	"@poly",
	"@mega",
	"@quad",
	"@oct",
	"@risso",
	"@minke",
	"@bryde",
	"@sei",
	"@omura",
	"@retusa",
	"@oxynoe",
	"@cyerce",
	"@aegires",
	"@navanax",
	"@alpha",
	"@beta",
	"@gamma",
	"@stell",
	"@locus",
	"@precept",
	"@vanquish",
	"@conquer",
	"@merui",
	"@cleroi",
	"@anthicus",
	"@tecta",
	"@collaris",
	"@elude",
	"@avert",
	"@obviate",
	"@quell",
	"@disrupt",
	"@evoke",
	"@incite",
	"@emanate",
	"@copper",
	"@lead",
	"@metaglass",
	"@graphite",
	"@coal",
	"@sand",
	"@titanium",
	"@thorium",
	"@scrap",
	"@silicon",
	"@plastanium",
	"@phase-fabric",
	"@surge-alloy",
	"@spore-pod",
	"@blast-compound",
	"@pyratite",
	"@berrylium",
	"@tungsten",
	"@oxide",
	"@carbide",
	"@water",
	"@slag",
	"@oil",
	"@cryofluid",
	"@neoplasm",
	"@arkycite",
	"@ozone",
	"@hydrogen",
	"@nitrogen",
	"@cyanogen"
]
